load("@rules_cc//cc:defs.bzl", "cc_binary")
load("@rules_python//python:defs.bzl", "py_binary")

cc_binary(
    name = "romtest",
    srcs = ["src/main.cpp"],
    deps = [
        "//core",
        "//nes",
        "@fmt",
    ],
)

py_binary(
    name = "test_rom",
    srcs = ["test_rom.py"],
    args = [
        "--romtest-bin",
        "$(rootpath :romtest)",
    ],
    data = [":romtest"],
    main = "test_rom.py",
)
