#pragma once

#include <cstdint>

namespace n_e_s::core {

enum Instruction : uint8_t {
    BrkImplied = 0x00,
    PhpImplied = 0x08,
    BplRelative = 0x10,
    ClcImplied = 0x18,
    JsrAbsolute = 0x20,
    BitZeropage = 0x24,
    BitAbsolute = 0x2C,
    BmiRelative = 0x30,
    SecImplied = 0x38,
    PhaImplied = 0x48,
    LsrAccumulator = 0x4A,
    JmpAbsolute = 0x4C,
    BvcRelative = 0x50,
    CliImplied = 0x58,
    RtsImplied = 0x60,
    AdcZeropage = 0x65,
    AdcImmediate = 0x69,
    AdcAbsolute = 0x6D,
    BvsRelative = 0x70,
    SeiImplied = 0x78,
    StaIndexedIndirect = 0x81,
    StyZeropage = 0x84,
    StaZeropage = 0x85,
    StxZeropage = 0x86,
    DeyImplied = 0x88,
    TxaImplied = 0x8A,
    StyAbsolute = 0x8C,
    StaAbsolute = 0x8D,
    StxAbsolute = 0x8E,
    BccRelative = 0x90,
    StaIndirectIndexed = 0x91,
    StyZeropageX = 0x94,
    StaZeropageX = 0x95,
    StxZeropageY = 0x96,
    TyaImplied = 0x98,
    StaAbsoluteY = 0x99,
    TxsImplied = 0x9A,
    StaAbsoluteX = 0x9D,
    LdyImmediate = 0xA0,
    LdxImmediate = 0xA2,
    LdyZeropage = 0xA4,
    LdaZeropage = 0xA5,
    LdxZeropage = 0xA6,
    TayImplied = 0xA8,
    LdaImmediate = 0xA9,
    TaxImplied = 0xAA,
    LdyAbsolute = 0xAC,
    LdaAbsolute = 0xAD,
    LdxAbsolute = 0xAE,
    BcsRelative = 0xB0,
    LdyZeropageX = 0xB4,
    LdaZeropageX = 0xB5,
    LdxZeropageY = 0xB6,
    ClvImplied = 0xB8,
    TsxImplied = 0xBA,
    CpyImmediate = 0xC0,
    CpyZeropage = 0xC4,
    InyImplied = 0xC8,
    DexImplied = 0xCA,
    CpyAbsolute = 0xCC,
    BneRelative = 0xD0,
    CldImplied = 0xD8,
    CpxImmediate = 0xE0,
    CpxZeropage = 0xE4,
    InxImplied = 0xE8,
    NopImplied = 0xEA,
    CpxAbsolute = 0xEC,
    BeqRelative = 0xF0,
    SedImplied = 0xF8,
};

enum class Family {
    Invalid,
    BRK,
    PHP,
    BPL,
    CLC,
    BIT,
    JSR,
    BMI,
    SEC,
    LSR,
    PHA,
    JMP,
    BVC,
    CLI,
    ADC,
    RTS,
    BVS,
    SEI,
    STY,
    STA,
    STX,
    TXS,
    BCC,
    LDX,
    LDY,
    LDA,
    BCS,
    CLV,
    BNE,
    CLD,
    CPX,
    NOP,
    INX,
    INY,
    CPY,
    BEQ,
    SED,
    TYA,
    TAY,
    TAX,
    TSX,
    TXA,
    DEY,
    DEX,
};

enum class AddressMode {
    Implied,
    Immediate,
    Zeropage,
    ZeropageX,
    ZeropageY,
    Relative,
    Absolute,
    AbsoluteX,
    AbsoluteY,
    Accumulator,
    IndexedIndirect,
    IndirectIndexed
};

struct Opcode {
    Family family;
    Instruction instruction;
    AddressMode address_mode;
};

Opcode decode(const uint8_t op);

} // namespace n_e_s::core
