load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

cc_library(
    name = "core",
    srcs = glob([
        "src/**",
    ]),
    hdrs = glob([
        "include/**/*.h",
    ]),
    local_includes = ["src/"],
    strip_include_prefix = "include/",
    visibility = ["//visibility:public"],
    deps = [
        "@fmt",
    ],
)

cc_library(
    name = "core_test_utils",
    hdrs = glob([
        "test_utils/include/**/*.h",
    ]),
    strip_include_prefix = "test_utils/include/",
    visibility = ["//visibility:public"],
    deps = [
        ":core",
        "@fmt",
        "@googletest//:gtest",
    ],
)

cc_test(
    name = "core_test",
    size = "small",
    srcs = glob([
        "test/src/*.cpp",
        "test/src/*.h",
    ]),
    deps = [
        ":core",
        ":core_test_utils",
        "@fmt",
        "@googletest//:gtest",
    ],
)
